FROM rust:1.86.0-slim-bookworm

WORKDIR /app

COPY Cargo.toml ./

COPY src/* src/
COPY static/* static/


RUN apt-get update
RUN apt-get install -y pkg-config libssl-dev perl make

RUN cargo build --release

EXPOSE 8080

CMD ["./target/release/lolepic"]