services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .env.secret
    depends_on:
      postgres:
        condition: service_started
      postgres-init:
        condition: service_completed_successfully
    profiles:
      - prod
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .env.secret
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /target
    profiles:
      - dev

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
      - .env.secret
    volumes:
      - ${PWD}/postgres-data/:/var/lib/postgresql/data/

  postgres-sqlx:
    build:
      context: .
      dockerfile: Dockerfile.sqlx_user
    stdin_open: true # docker run -i
    tty: true # docker run -t
    env_file:
      - .env
      - .env.secret
    depends_on:
      - postgres
    profiles:
      - disabled

  postgres-init:
    build:
      context: .
      dockerfile: Dockerfile.postgres-init
    env_file:
      - .env
      - .env.secret
    depends_on:
      - postgres
