version: "3"
services:
  app:
    build: Dockerfile
    restart: always
    ports:
      - "8083:8080"
    env_file:
      - .env
      - .env.secret
    depends_on:
      - postgres
    networks:
      - lolepic-postgres
  dev-app:
    build: Dockerfile.dev
    ports:
      - "8083:8080"
    env_file:
      - .env
      - .env.secret
    depends_on:
      - postgres
    networks:
      - lolepic-postgres
    profiles: dev

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
      - .env.secret
    networks:
      - lolepic-postgres
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4:4.23
    restart: always
    env_file:
      - .env
      - .env.secret
    environment:
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  lolepic-postgres:
